version: "3.7"

services:
  database_node_prisma:
    image: postgres
    container_name: database_node_prisma
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=node_prisma
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: node_prisma
    ports:
      - 3333:3333
    environment:
      DATABASE_URL: "postgresql://root:toor@database_node_prisma:5432/node_prisma?schema=public"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules/bcrypt/
    links:
      - database_node_prisma
    depends_on:
      - database_node_prisma
      
volumes:
  pgdata:
    driver: local      
