version: "3.7"

services:
  database_node_prisma:
    image: postgres
    container_name: database_node_prisma
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=node_prisma
    volumes:
      - pgdata:/data/
      
volumes:
  pgdata:
    driver: local      
